services:
  - type: cron
    name: automation
    env: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 * * * *"  # Every hour
    envVars:
      - key: BW_EMAIL
        sync: false
      - key: BW_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
      - key: PS_EMAIL
        sync: false
      - key: PS_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

      

